// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Bookmark struct {
	ID           string      `json:"id"`
	Title        string      `json:"title"`
	URL          string      `json:"url"`
	Description  *string     `json:"description,omitempty"`
	Notes        *string     `json:"notes,omitempty"`
	Favicon      *string     `json:"favicon,omitempty"`
	Screenshot   *string     `json:"screenshot,omitempty"`
	Tags         []string    `json:"tags,omitempty"`
	CollectionID string      `json:"collectionId"`
	Collection   *Collection `json:"collection"`
	UserID       string      `json:"userId"`
	User         *User       `json:"user"`
	CreatedAt    string      `json:"createdAt"`
	UpdatedAt    string      `json:"updatedAt"`
}

type BookmarkFilter struct {
	Search       *string  `json:"search,omitempty"`
	Tags         []string `json:"tags,omitempty"`
	CollectionID *string  `json:"collectionId,omitempty"`
}

type Collection struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description,omitempty"`
	Color       *string     `json:"color,omitempty"`
	UserID      string      `json:"userId"`
	User        *User       `json:"user"`
	Bookmarks   []*Bookmark `json:"bookmarks"`
	CreatedAt   string      `json:"createdAt"`
	UpdatedAt   string      `json:"updatedAt"`
}

type CreateBookmarkInput struct {
	Title        string   `json:"title"`
	URL          string   `json:"url"`
	Description  *string  `json:"description,omitempty"`
	Notes        *string  `json:"notes,omitempty"`
	Tags         []string `json:"tags,omitempty"`
	CollectionID string   `json:"collectionId"`
}

type CreateCollectionInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Color       *string `json:"color,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type UpdateBookmarkInput struct {
	Title        *string  `json:"title,omitempty"`
	URL          *string  `json:"url,omitempty"`
	Description  *string  `json:"description,omitempty"`
	Notes        *string  `json:"notes,omitempty"`
	Tags         []string `json:"tags,omitempty"`
	CollectionID *string  `json:"collectionId,omitempty"`
}

type UpdateCollectionInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Color       *string `json:"color,omitempty"`
}

type User struct {
	ID          string        `json:"id"`
	Email       string        `json:"email"`
	Username    string        `json:"username"`
	CreatedAt   string        `json:"createdAt"`
	UpdatedAt   string        `json:"updatedAt"`
	Collections []*Collection `json:"collections"`
}
